### ISSUE TITLE
Question about the function of this

### ISSUE THREAD

**Issue by 10481** [nhubbard/MagicPlugins#4]
It says that it places snow in the background. To me, that sounds like the snow should run down the mirror behind the existing modules showing the modules and the snow, but for me, it either runs over top of all of them making them not visible (snow only) or behind them out of site. Can the read me elaborate a little bit more?

**Comment by nhubbard** [comment]
That sounds very odd, @10481. Where did you add the module in your config.js? It should be the last module in the list of modules.

**Comment by 10481** [comment]
I tried both at the top and the bottom. Top it overlays everything with the black background so it's only snow and the bottom it runs behind. I see it start up and then the other modules cover it. The only step I ignored was forking the repo and just manually created the files. That wouldn't cause any issue though, would it?

**Comment by nhubbard** [comment]
It shouldn't do that. I'm using on my own Magic Mirror, and it just sits in the background, because the way I programmed it set the background to be black with animation. It shouldn't cover the mirror interface.

**Edit:** Are you setting a position on the module? The module block configuration should look like this:

```javascript
{
  "module": "snow"
}

**Comment by keithmackay** [comment]
I had an "all-black mirror" problem, too -- but found that moving the "snow" folder to be a direct child of the "modules" folder fixed my issue (I'd pulled my fork to the wrong path...). Thanks Nick (and all!) for a fun project and great set of modules.

**Comment by nhubbard** [comment]
Thanks, @keithmackay!

**Comment by 10481** [comment]
Ah, good to know! Thanks. I'll do that next year!
